title = "Hide and Seek"
version = "1.0.0"
author = "Flumzee"

sources = "src"
output = "build"
docs = "docs"

language = "en"

gitRepoUrl = "https://github.com/scriptlabs-rblx/hideandseek.git"
gitSourceBranch = "main"